#ifndef OF_GAMESTATES_MENU_MAPLIST_H
#define OF_GAMESTATES_MENU_MAPLIST_H

#define MAPLIST_MINIMAP_X 120
#define MAPLIST_MINIMAP_Y 10
#define MAPLIST_MINIMAP_WIDTH 128

#endif // OF_GAMESTATES_MENU_MAPLIST_H
